# Site settings
title:          Field Notes
description:    "Dispatches from ordinary life."
baseurl:        ""
url:            "https://brettwagner.me"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Brett Wagner
  url:          https://brettwagner.me
  email:        brettwagner78@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       6

# Menu Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "New"
    url: "/new"
  - title: "Sermons"
    url: "https://www.sermonaudio.com/speakers/27123"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, .DS_Store ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale